-- Seed structured Management Summary values for all countries.
-- Values are editable via /edit/countries/:id afterwards; idempotent updates
-- by code so re-running does not break anything but will overwrite edits.
-- NOTE: Values are best-effort reference data — please review before relying on.

UPDATE countries SET currency='EUR', central_bank='Deutsche Bundesbank', iso20022_status='Ja (CBPR+ / SEPA pain.001.001.09)', instant_payments='Ja — SCT Inst (TIPS, RT1)', intercompany_netting='Ja', cash_pooling_external='Ja — Notional & Physical', pobo='Ja', pino_routing='Ja — Standard SEPA CT/Inst', special_format_requirements='EBICS T+TS Standard; DTAZV für Auslandszahlungen auslaufend', special_regulatory_requirements='ZAG, KWG, AWV-Meldepflicht ≥ EUR 12.500, GwG' WHERE code='DE';

UPDATE countries SET currency='EUR', central_bank='Oesterreichische Nationalbank (OeNB)', iso20022_status='Ja (SEPA pain.001.001.09)', instant_payments='Ja — SCT Inst', intercompany_netting='Ja', cash_pooling_external='Ja — Notional & Physical', pobo='Ja', pino_routing='Ja — Standard SEPA CT/Inst', special_format_requirements='OeNB Creditor Identifier für SDD; DatenTrägerAustausch-Verordnung', special_regulatory_requirements='ZaDiG, BWG, OeNB-Meldung ≥ EUR 100.000, GwG' WHERE code='AT';

UPDATE countries SET currency='CHF (EUR parallel)', central_bank='Schweizerische Nationalbank (SNB)', iso20022_status='Ja — SIC5 verpflichtend seit 2023', instant_payments='Ja — SIC IP seit August 2024', intercompany_netting='Ja', cash_pooling_external='Ja — Notional & Physical', pobo='Ja', pino_routing='CHF via SIC; EUR via SEPA/euroSIC', special_format_requirements='CH-pain.001 (SIX Swiss Payment Standards) weicht vom EPC-Rulebook ab; QR-Rechnung Pflicht', special_regulatory_requirements='FINMA, GwG (CH), SNB-Statistikmeldung, Quellensteuer auf Zinsen' WHERE code='CH';

UPDATE countries SET currency='EUR', central_bank='De Nederlandsche Bank (DNB)', iso20022_status='Ja (SEPA pain.001.001.09)', instant_payments='Ja — SCT Inst (24/7 seit 2019)', intercompany_netting='Ja', cash_pooling_external='Ja — Notional Pooling gut etabliert', pobo='Ja', pino_routing='Ja — Standard SEPA CT/Inst', special_format_requirements='iDEAL als dominantes Consumer-Instrument; SEPA Standard für Corporates', special_regulatory_requirements='Wft, DNB-Meldung ≥ EUR 50.000, Wwft (AML)' WHERE code='NL';

UPDATE countries SET currency='EUR', central_bank='Nationale Bank van België (NBB)', iso20022_status='Ja (SEPA pain.001.001.09)', instant_payments='Ja — SCT Inst', intercompany_netting='Ja', cash_pooling_external='Ja', pobo='Ja', pino_routing='Ja — Standard SEPA CT/Inst', special_format_requirements='NBB Creditor Identifier für SDD; strukturierte Mitteilung (+++/+++)', special_regulatory_requirements='NBB-Aufsicht, GwG-BE, regionale Feiertage' WHERE code='BE';

UPDATE countries SET currency='EUR', central_bank='Banque centrale du Luxembourg (BCL)', iso20022_status='Ja (SEPA pain.001.001.09)', instant_payments='Ja — SCT Inst', intercompany_netting='Ja', cash_pooling_external='Ja — sehr verbreitet', pobo='Ja', pino_routing='Ja — Standard SEPA CT/Inst', special_format_requirements='CSSF-Anforderungen für Finanzinstitute; Standard SEPA für Corporates', special_regulatory_requirements='CSSF, Meldung ≥ EUR 50.000, GwG' WHERE code='LU';

UPDATE countries SET currency='EUR', central_bank='Banque de France (BdF)', iso20022_status='Ja (SEPA pain.001.001.09)', instant_payments='Ja — SCT Inst', intercompany_netting='Ja', cash_pooling_external='Ja — Notional (mit Einschränkungen)', pobo='Ja', pino_routing='Ja — Standard SEPA; LCR/BOR rückläufig', special_format_requirements='Chorus Pro e-Invoicing B2G Pflicht; B2B stufenweise ab 2026', special_regulatory_requirements='ACPR, BdF CI, Meldung ≥ EUR 50.000, LCB-FT (AML)' WHERE code='FR';

UPDATE countries SET currency='EUR', central_bank='Banca d''Italia', iso20022_status='Ja (SEPA pain.001.001.09) + CBI-Variante', instant_payments='Ja — SCT Inst (TIPS)', intercompany_netting='Ja', cash_pooling_external='Ja — Eingeschränkt (Zinsabzug)', pobo='Ja', pino_routing='SEPA CT/Inst; CBI-Format für lokale Banken', special_format_requirements='CBI/CBILL für lokale Banken; Fattura Elettronica (SDI) Pflicht seit 2019; Codice Fiscale in Zahlung', special_regulatory_requirements='Banca d''Italia, UIF, GwG (IT), elektronische Rechnungspflicht' WHERE code='IT';

UPDATE countries SET currency='EUR', central_bank='Banco de España', iso20022_status='Ja (SEPA pain.001.001.09)', instant_payments='Ja — SCT Inst (Bizum sehr verbreitet)', intercompany_netting='Ja', cash_pooling_external='Ja', pobo='Ja', pino_routing='Ja — Standard SEPA CT/Inst', special_format_requirements='NIF/CIF Pflicht in bestimmten Zahlungen; Cuaderno 34/43 legacy', special_regulatory_requirements='Banco de España, Verifactu (B2B e-Invoicing in Vorbereitung), SEPBLAC (AML)' WHERE code='ES';

UPDATE countries SET currency='EUR', central_bank='Banco de Portugal', iso20022_status='Ja (SEPA pain.001.001.09)', instant_payments='Ja — SCT Inst; MB WAY Consumer', intercompany_netting='Ja', cash_pooling_external='Ja', pobo='Ja', pino_routing='Ja — Standard SEPA CT/Inst', special_format_requirements='NIF in Zahlungen empfohlen; SAF-T Reporting; AT e-Invoice B2G', special_regulatory_requirements='Banco de Portugal, AT (Autoridade Tributária), GwG-PT' WHERE code='PT';

UPDATE countries SET currency='EUR', central_bank='Bank of Greece (Τράπεζα της Ελλάδος)', iso20022_status='Ja (SEPA pain.001.001.09)', instant_payments='Teilweise — SCT Inst im Ausbau', intercompany_netting='Ja', cash_pooling_external='Ja — eingeschränkt', pobo='Ja — eingeschränkt', pino_routing='Standard SEPA CT; Inst begrenzt', special_format_requirements='myDATA digitale Buchführungspflicht seit 2021; AFM als Steuer-ID', special_regulatory_requirements='Bank of Greece, AADE, Kapitalverkehrsmeldepflichten' WHERE code='GR';

UPDATE countries SET currency='SEK (EUR parallel)', central_bank='Sveriges Riksbank', iso20022_status='Ja — EUR via SEPA; SEK Bankgirot migriert', instant_payments='Ja — Swish (Consumer); RIX-INST für SEK', intercompany_netting='Ja', cash_pooling_external='Ja — Notional & Physical', pobo='Ja', pino_routing='EUR via SEPA; SEK via BiR/RIX', special_format_requirements='Bankgiro/Plusgiro Referenznummern; OCR-Reference; SCT Inst SEK Pflicht ab Jan 2027', special_regulatory_requirements='Finansinspektionen, Riksbank, GwG-SE' WHERE code='SE';

UPDATE countries SET currency='DKK (EUR parallel)', central_bank='Danmarks Nationalbank', iso20022_status='Ja — EUR via SEPA; DKK-Clearing migriert', instant_payments='Ja — Straksclearing (DKK Instant); MobilePay', intercompany_netting='Ja', cash_pooling_external='Ja', pobo='Ja', pino_routing='EUR via SEPA; DKK via Nets/Straksclearing', special_format_requirements='FIK/GIK-Referenznummern; OIOUBL e-Invoice B2G Pflicht', special_regulatory_requirements='Finanstilsynet, Nationalbank-Meldung, GwG-DK' WHERE code='DK';

UPDATE countries SET currency='NOK', central_bank='Norges Bank', iso20022_status='Ja — NICS Migration ISO 20022', instant_payments='Ja — Straksbetaling; Vipps Consumer', intercompany_netting='Ja', cash_pooling_external='Ja', pobo='Ja', pino_routing='NOK via NICS; internationale Zahlungen SWIFT/SEPA (CHF/EUR)', special_format_requirements='KID-Nummer als strukturierte Referenz; EHF e-Invoice B2G', special_regulatory_requirements='Finanstilsynet, Norges Bank-Meldung, Hvitvaskingsloven (AML)' WHERE code='NO';

UPDATE countries SET currency='EUR', central_bank='Suomen Pankki / Bank of Finland', iso20022_status='Ja (SEPA pain.001.001.09)', instant_payments='Ja — SCT Inst; Siirto/Pivo', intercompany_netting='Ja', cash_pooling_external='Ja', pobo='Ja', pino_routing='Ja — Standard SEPA CT/Inst', special_format_requirements='Finvoice e-Invoice B2B weit verbreitet; TITO Kontoauszug', special_regulatory_requirements='FIN-FSA, Bank of Finland, GwG-FI' WHERE code='FI';

UPDATE countries SET currency='PLN (EUR parallel)', central_bank='Narodowy Bank Polski (NBP)', iso20022_status='Teilweise — ELIXIR migriert stufenweise', instant_payments='Ja — Express Elixir; BLIK (Consumer)', intercompany_netting='Ja', cash_pooling_external='Ja — Notional (mit NBP-Genehmigung)', pobo='Ja — eingeschränkt', pino_routing='PLN via ELIXIR; EUR via SEPA/EuroELIXIR', special_format_requirements='NIP als Steuer-ID Pflicht; KSeF e-Invoicing Pflicht geplant (verschoben)', special_regulatory_requirements='KNF, NBP-Meldung ≥ EUR 15.000, Split Payment VAT, AML-PL' WHERE code='PL';

UPDATE countries SET currency='CZK (EUR parallel)', central_bank='Česká národní banka (ČNB)', iso20022_status='Ja (CERTIS Migration)', instant_payments='Ja — CERTIS Instant', intercompany_netting='Ja', cash_pooling_external='Ja', pobo='Ja', pino_routing='CZK via CERTIS; EUR via SEPA', special_format_requirements='IČO als Unternehmens-ID in Transaktionen; Variabilní/Konstantní symbol', special_regulatory_requirements='ČNB, FAÚ (AML), Kontrollní hlášení VAT-Reporting' WHERE code='CZ';

UPDATE countries SET currency='HUF (EUR parallel)', central_bank='Magyar Nemzeti Bank (MNB)', iso20022_status='Ja — AFR verpflichtet ISO 20022', instant_payments='Ja — AFR (HUF Instant 24/7, Pflicht seit März 2020)', intercompany_netting='Ja', cash_pooling_external='Ja — mit Einschränkungen', pobo='Ja — eingeschränkt', pino_routing='HUF via AFR/GIRO; EUR via SEPA', special_format_requirements='Adószám als Steuer-ID Pflicht; NAV Online Számla Echtzeit-Reporting', special_regulatory_requirements='MNB, NAV Echtzeit-Rechnungsmeldung, AML-HU' WHERE code='HU';

UPDATE countries SET currency='RON (EUR parallel)', central_bank='Banca Națională a României (BNR)', iso20022_status='Ja — SENT migriert', instant_payments='Ja — Plăți Instant', intercompany_netting='Ja', cash_pooling_external='Ja — eingeschränkt', pobo='Ja — eingeschränkt', pino_routing='RON via SENT/ReGIS; EUR via SEPA', special_format_requirements='CUI als Unternehmens-ID; e-Factura Pflicht seit Jan 2024 für B2B', special_regulatory_requirements='BNR, ANAF, SAF-T Reporting, AML-RO' WHERE code='RO';

UPDATE countries SET currency='GBP', central_bank='Bank of England', iso20022_status='Ja — CHAPS migriert (ISO 20022 seit 2023); FPS in Migration', instant_payments='Ja — Faster Payments (FPS, bis GBP 1 Mio)', intercompany_netting='Ja', cash_pooling_external='Ja — sehr etabliert (London als Hub)', pobo='Ja', pino_routing='GBP via CHAPS (RTGS) / FPS (Instant) / BACS (Batch)', special_format_requirements='Sort Code + Kontonummer statt IBAN im Inland; BACS 18-Zeichen-Format legacy', special_regulatory_requirements='FCA, PRA, UK PSD2, Post-Brexit eigene Lizenzierung, AML-UK' WHERE code='GB';

UPDATE countries SET currency='EUR', central_bank='Central Bank of Ireland (CBI)', iso20022_status='Ja (SEPA pain.001.001.09)', instant_payments='Ja — SCT Inst', intercompany_netting='Ja', cash_pooling_external='Ja — sehr beliebt als EU-Treasury-Hub', pobo='Ja', pino_routing='Ja — Standard SEPA CT/Inst', special_format_requirements='Standard SEPA; keine lokalen Besonderheiten', special_regulatory_requirements='CBI, Revenue, Criminal Justice Act (AML)' WHERE code='IE';

UPDATE countries SET currency='CNY / RMB', central_bank='People''s Bank of China (PBoC)', iso20022_status='Ja — CIPS ISO 20022 nativ', instant_payments='Ja — IBPS (inländisch)', intercompany_netting='Nein — SAFE-Genehmigung nötig', cash_pooling_external='Nein — nur Cross-Border Cash Pooling Pilot (Shanghai FTZ u.ä.)', pobo='Nein — verboten', pino_routing='CNY onshore via CNAPS; offshore via CIPS', special_format_requirements='VAT Fapiao Pflicht; Purpose Code für grenzüberschreitende Zahlungen', special_regulatory_requirements='SAFE-Devisenkontrolle, PBoC, strenge Dokumentationspflichten, Datenlokalisierung' WHERE code='CN';

UPDATE countries SET currency='JPY', central_bank='Bank of Japan (BoJ)', iso20022_status='Teilweise — Zengin-System Migration laufend', instant_payments='Ja — Zengin System (24/7 seit 2018)', intercompany_netting='Ja — mit BoJ-Meldung', cash_pooling_external='Ja — etabliert', pobo='Ja', pino_routing='JPY via Zengin (inländisch) / BOJ-NET (RTGS)', special_format_requirements='Zengin-Format statt IBAN; Katakana-Pflicht für Empfängernamen; Golden Week Bankfeiertage', special_regulatory_requirements='FSA, BoJ-Meldepflicht > JPY 30 Mio, Foreign Exchange Act' WHERE code='JP';

UPDATE countries SET currency='AUD', central_bank='Reserve Bank of Australia (RBA)', iso20022_status='Ja — NPP ISO 20022 nativ', instant_payments='Ja — NPP mit PayID (seit 2018)', intercompany_netting='Ja', cash_pooling_external='Ja', pobo='Ja', pino_routing='AUD via NPP/BECS/RITS', special_format_requirements='BSB (6-stellig) + Kontonummer statt IBAN; PayID als Alias', special_regulatory_requirements='APRA, RBA, AUSTRAC (AML), Foreign Investment Review' WHERE code='AU';

UPDATE countries SET currency='SGD', central_bank='Monetary Authority of Singapore (MAS)', iso20022_status='Ja — FAST/MEPS+ ISO 20022 nativ', instant_payments='Ja — FAST (24/7); PayNow', intercompany_netting='Ja', cash_pooling_external='Ja — sehr etabliert (APAC-Hub)', pobo='Ja', pino_routing='SGD via FAST (Instant) / MEPS+ (RTGS)', special_format_requirements='PayNow mit UEN/Mobile als Proxy; Standard SWIFT international', special_regulatory_requirements='MAS, unternehmensfreundliche Regulierung, AML-SG' WHERE code='SG';

UPDATE countries SET currency='INR', central_bank='Reserve Bank of India (RBI)', iso20022_status='Teilweise — NEFT/RTGS ISO 20022 Migration laufend', instant_payments='Ja — IMPS/UPI (24/7)', intercompany_netting='Nein — FEMA-Einschränkungen', cash_pooling_external='Nein — nicht zulässig', pobo='Nein — verboten', pino_routing='INR via NEFT/RTGS/IMPS/UPI; SWIFT international', special_format_requirements='IFSC Code + Kontonummer statt IBAN; PAN/GSTIN in Zahlungen; RBI Purpose Code', special_regulatory_requirements='FEMA-Devisenkontrolle, RBI, TDS auf IC-Zinsen, GST Reporting' WHERE code='IN';

UPDATE countries SET currency='USD', central_bank='Federal Reserve System (Fed)', iso20022_status='Ja — FedNow/CHIPS ISO 20022; Fedwire Migration 2025', instant_payments='Ja — FedNow (seit 2023); RTP (TCH)', intercompany_netting='Ja', cash_pooling_external='Ja — sehr etabliert', pobo='Ja — State-Lizenzen prüfen (Money Transmitter Laws)', pino_routing='USD via Fedwire (RTGS) / ACH (NACHA) / CHIPS / FedNow / RTP', special_format_requirements='NACHA-Format für ACH; Routing/ABA-Number statt IBAN; Check 21 legacy', special_regulatory_requirements='OFAC-Screening weltweit für USD, FinCEN, State Money Transmitter Laws, FATCA' WHERE code='US';

UPDATE countries SET currency='CAD', central_bank='Bank of Canada', iso20022_status='Ja — Lynx ISO 20022 (seit 2021); RTR in Einführung', instant_payments='In Einführung — RTR verzögert; Interac e-Transfer Consumer', intercompany_netting='Ja', cash_pooling_external='Ja', pobo='Ja', pino_routing='CAD via Lynx (RTGS) / ACSS (Batch) / AFT', special_format_requirements='Transit Number (5) + Institution (3) + Kontonummer statt IBAN; bilingual EN/FR in Québec', special_regulatory_requirements='OSFI, FINTRAC (AML), Payments Canada Rules' WHERE code='CA';

UPDATE countries SET currency='BRL', central_bank='Banco Central do Brasil (BCB)', iso20022_status='Ja — SPI (PIX) ISO 20022 nativ', instant_payments='Ja — PIX (24/7, seit 2020)', intercompany_netting='Nein — BCB-Genehmigung nötig', cash_pooling_external='Nein — nicht zulässig', pobo='Nein — verboten', pino_routing='BRL via PIX/TED/DOC; Cross-border streng reguliert', special_format_requirements='NF-e Pflicht für alle Transaktionen; CNPJ in Zahlungen; SAP BR-Add-On (Localization)', special_regulatory_requirements='BCB, Receita Federal, IOF-Steuer auf Devisenzahlungen, COAF (AML)' WHERE code='BR';

UPDATE countries SET currency='MXN', central_bank='Banco de México (Banxico)', iso20022_status='Ja — SPEI ISO 20022 nativ', instant_payments='Ja — SPEI (24/7)', intercompany_netting='Ja — mit Dokumentation', cash_pooling_external='Ja — eingeschränkt', pobo='Ja — mit SAT-Compliance', pino_routing='MXN via SPEI (Instant RTGS) / SPID (USD-Pendant)', special_format_requirements='CLABE (18-stellig) statt IBAN; CFDI e-Invoice Pflicht; RFC als Steuer-ID', special_regulatory_requirements='Banxico, CNBV, SAT (strenge Compliance), AML-MX' WHERE code='MX';

UPDATE countries SET currency='AED', central_bank='Central Bank of the UAE (CBUAE)', iso20022_status='Ja — UAEFTS ISO 20022', instant_payments='Ja — IPP (Instant Payment Platform, Aani)', intercompany_netting='Ja', cash_pooling_external='Ja', pobo='Ja', pino_routing='AED via UAEFTS (RTGS) / IPP (Instant)', special_format_requirements='Standard IBAN; DIFC/ADGM Free Zones mit eigenen Regelwerken', special_regulatory_requirements='CBUAE, DFSA/FSRA in Free Zones, AML-UAE, 9% Corporate Tax seit 2023' WHERE code='AE';

UPDATE countries SET currency='SAR', central_bank='Saudi Central Bank (SAMA)', iso20022_status='Ja — SARIE ISO 20022', instant_payments='Ja — sarie instant / IPS', intercompany_netting='Ja — eingeschränkt', cash_pooling_external='Ja — eingeschränkt', pobo='Ja — eingeschränkt', pino_routing='SAR via SARIE (RTGS) / IPS (Instant)', special_format_requirements='Fatoora e-Invoice Pflicht (ZATCA Phase 1+2); VAT 15%', special_regulatory_requirements='SAMA, ZATCA, Wochenende Fr+Sa, AML-SA' WHERE code='SA';

UPDATE countries SET currency='ZAR', central_bank='South African Reserve Bank (SARB)', iso20022_status='Teilweise — Migration in Arbeit (Payments Modernisation Programme)', instant_payments='Ja — PayShap (seit 2023)', intercompany_netting='Nein — SARB-Genehmigung nötig', cash_pooling_external='Eingeschränkt — SARB Exchange Control', pobo='Eingeschränkt', pino_routing='ZAR via SAMOS (RTGS) / EFT / PayShap', special_format_requirements='ZAEFT-Format proprietär; Branch Code (6) + Kontonummer', special_regulatory_requirements='SARB Exchange Control, FSCA, FIC Act (AML), Meldepflicht > ZAR 1 Mio' WHERE code='ZA';
