import { registerFormat } from '@/lib/formats/registry';
import type { StructureNode, MigrationChange } from '@/lib/formats/types';

const structure: StructureNode[] = [
  {
    name: 'FIToFICstmrCdtTrf',
    card: '1',
    type: 'FIToFICustomerCreditTransferV<vv>',
    desc: 'Wurzelelement — FI-to-FI Customer Credit Transfer. Interbank-Leg einer SCT / SCT-Inst / Cross-Border-Zahlung.',
    children: [
      {
        name: 'GrpHdr',
        card: '1',
        type: 'GroupHeader93',
        desc: 'Header der Interbank-Nachricht. Gilt für ALLE Transaktionen im Block.',
        children: [
          { name: 'MsgId', card: '1', type: 'Max35Text', desc: 'Eindeutige Message-ID des sendenden Agenten.' },
          { name: 'CreDtTm', card: '1', type: 'ISODateTime', desc: 'Erstellungs-Zeitstempel der Interbank-Nachricht.' },
          { name: 'NbOfTxs', card: '1', type: 'Max15NumericText', desc: 'Anzahl Einzeltransaktionen (CdtTrfTxInf).' },
          { name: 'CtrlSum', card: '0..1', type: 'DecimalNumber', desc: 'Kontrollsumme aller IntrBkSttlmAmt.' },
          { name: 'TtlIntrBkSttlmAmt', card: '0..1', type: 'ActiveCurrencyAndAmount', desc: 'Summe aller Interbank-Settlement-Beträge.' },
          { name: 'IntrBkSttlmDt', card: '0..1', type: 'ISODate', desc: 'Settlement-Datum zwischen den Banken.' },
          {
            name: 'SttlmInf',
            card: '1',
            type: 'SettlementInstruction7',
            desc: 'Settlement-Methode zwischen den beteiligten Banken.',
            children: [
              { name: 'SttlmMtd', card: '1', type: 'SettlementMethod1Code', desc: 'INDA (Instructed Agent), INGA (Instructing Agent), COVE (Cover), CLRG (Clearing System).' },
              { name: 'SttlmAcct', card: '0..1', type: 'CashAccount40', desc: 'Settlement-Konto, wenn nicht über Clearing.' },
              { name: 'ClrSys', card: '0..1', type: 'ClearingSystemIdentification3Choice', desc: 'Verwendetes Clearing-System (z.B. TARGET2, EURO1, RTGS).' },
            ],
          },
          { name: 'InstgAgt', card: '0..1', type: 'BranchAndFinancialInstitutionIdentification6', desc: 'Instructing Agent — Bank, die die Nachricht sendet.' },
          { name: 'InstdAgt', card: '0..1', type: 'BranchAndFinancialInstitutionIdentification6', desc: 'Instructed Agent — Bank, die die Nachricht empfängt.' },
        ],
      },
      {
        name: 'CdtTrfTxInf',
        card: '1..N',
        type: 'CreditTransferTransaction39',
        desc: 'Einzelne Interbank-Transaktion. Eine pro End-Kunden-Zahlung.',
        children: [
          {
            name: 'PmtId',
            card: '1',
            type: 'PaymentIdentification7',
            desc: 'Payment-Identifikation der Einzeltransaktion.',
            children: [
              { name: 'InstrId', card: '0..1', type: 'Max35Text', desc: 'Instruction-ID des sendenden Agenten.' },
              { name: 'EndToEndId', card: '1', type: 'Max35Text', desc: 'End-to-End-Referenz, unverändert durchgereicht bis zum Empfänger.' },
              { name: 'TxId', card: '0..1', type: 'Max35Text', desc: 'Transaction-ID, eindeutig zwischen Instgg und Instd.' },
              { name: 'UETR', card: '1', type: 'UUIDv4', desc: 'Unique End-to-end Transaction Reference — Pflicht in CBPR+ für gpi-Tracking.', versionFlag: 'CBPR+' },
              { name: 'ClrSysRef', card: '0..1', type: 'Max35Text', desc: 'Referenz des Clearing-Systems.' },
            ],
          },
          {
            name: 'PmtTpInf',
            card: '0..1',
            type: 'PaymentTypeInformation28',
            desc: 'Zahlungsart / Service Level / Local Instrument.',
            children: [
              { name: 'InstrPrty', card: '0..1', type: 'Priority2Code', desc: 'NORM / HIGH.' },
              { name: 'ClrChanl', card: '0..1', type: 'ClearingChannel2Code', desc: 'RTGS, RTNS, MPNS, BOOK.' },
              { name: 'SvcLvl', card: '0..N', type: 'ServiceLevel8Choice', desc: 'SEPA, INST, SDVA, URGP, G001-G004 (CBPR+).' },
              { name: 'LclInstrm', card: '0..1', type: 'LocalInstrument2Choice', desc: 'B2B / CORE bei SDD; CBPR+ Codes.' },
              { name: 'CtgyPurp', card: '0..1', type: 'CategoryPurpose1Choice', desc: 'CASH, CORT, INTC, SALA, SUPP, TAXS, TREA.' },
            ],
          },
          { name: 'IntrBkSttlmAmt', card: '1', type: 'ActiveCurrencyAndAmount', desc: 'Interbank-Settlement-Betrag in Settlement-Währung. Pflicht pro Transaktion.' },
          { name: 'IntrBkSttlmDt', card: '0..1', type: 'ISODate', desc: 'Settlement-Datum (kann GrpHdr überschreiben).' },
          { name: 'SttlmTmIndctn', card: '0..1', type: 'SettlementDateTimeIndication1', desc: 'Debit/Credit Date & Time (gpi Fee-Transparency).' },
          { name: 'SttlmTmReq', card: '0..1', type: 'SettlementTimeRequest2', desc: 'CLS-Time, Till-Time, From-Time, Reject-Time.' },
          { name: 'InstdAmt', card: '0..1', type: 'ActiveOrHistoricCurrencyAndAmount', desc: 'Ursprünglich instruierter Betrag (bei Currency-Conversion ungleich IntrBkSttlmAmt).' },
          { name: 'XchgRate', card: '0..1', type: 'BaseOneRate', desc: 'Angewendeter Wechselkurs.' },
          { name: 'ChrgBr', card: '1', type: 'ChargeBearerType1Code', desc: 'SLEV, SHAR, DEBT (OUR), CRED (BEN). Pflicht in pacs.008.' },
          { name: 'ChrgsInf', card: '0..N', type: 'Charges7', desc: 'Angefallene Gebühren vorheriger Agenten (Fee-Transparency gpi).' },
          { name: 'PrvsInstgAgt1', card: '0..1', type: 'BranchAndFinancialInstitutionIdentification6', desc: 'Previous Instructing Agent 1 — Agent-Chain Rückwärts.' },
          { name: 'PrvsInstgAgt1Acct', card: '0..1', type: 'CashAccount40', desc: 'Konto bei PrvsInstgAgt1.' },
          { name: 'PrvsInstgAgt2', card: '0..1', type: 'BranchAndFinancialInstitutionIdentification6', desc: 'Previous Instructing Agent 2.' },
          { name: 'PrvsInstgAgt3', card: '0..1', type: 'BranchAndFinancialInstitutionIdentification6', desc: 'Previous Instructing Agent 3.' },
          { name: 'InstgAgt', card: '0..1', type: 'BranchAndFinancialInstitutionIdentification6', desc: 'Aktuell instruierender Agent (Transaktions-Ebene).' },
          { name: 'InstdAgt', card: '0..1', type: 'BranchAndFinancialInstitutionIdentification6', desc: 'Aktuell instruierter Agent (Transaktions-Ebene).' },
          { name: 'IntrmyAgt1', card: '0..1', type: 'BranchAndFinancialInstitutionIdentification6', desc: 'Intermediary Agent 1 — Korrespondenzbank im Pfad.' },
          { name: 'IntrmyAgt1Acct', card: '0..1', type: 'CashAccount40', desc: 'Nostro/Loro-Konto bei IntrmyAgt1.' },
          { name: 'IntrmyAgt2', card: '0..1', type: 'BranchAndFinancialInstitutionIdentification6', desc: 'Intermediary Agent 2.' },
          { name: 'IntrmyAgt3', card: '0..1', type: 'BranchAndFinancialInstitutionIdentification6', desc: 'Intermediary Agent 3.' },
          { name: 'UltmtDbtr', card: '0..1', type: 'PartyIdentification135', desc: 'Ultimate Debtor (POBO — Original-Auftraggeber).' },
          { name: 'InitgPty', card: '0..1', type: 'PartyIdentification135', desc: 'Initiating Party aus pain.001.' },
          {
            name: 'Dbtr',
            card: '1',
            type: 'PartyIdentification135',
            desc: 'Schuldner / Zahler.',
            children: [
              { name: 'Nm', card: '0..1', type: 'Max140Text', desc: 'Name des Schuldners.' },
              { name: 'PstlAdr', card: '0..1', type: 'PostalAddress24', desc: 'Strukturierte Adresse — CBPR+ Pflicht ab Nov 2025.', versionFlag: 'CBPR+' },
              { name: 'Id', card: '0..1', type: 'Party38Choice', desc: 'OrgId (BIC/LEI/Other) oder PrvtId.' },
            ],
          },
          { name: 'DbtrAcct', card: '0..1', type: 'CashAccount40', desc: 'Schuldner-Konto (IBAN oder Othr).' },
          { name: 'DbtrAgt', card: '1', type: 'BranchAndFinancialInstitutionIdentification6', desc: 'Schuldner-Bank (BICFI).' },
          { name: 'DbtrAgtAcct', card: '0..1', type: 'CashAccount40', desc: 'Konto beim DbtrAgt.' },
          { name: 'CdtrAgt', card: '1', type: 'BranchAndFinancialInstitutionIdentification6', desc: 'Empfänger-Bank (BICFI).' },
          { name: 'CdtrAgtAcct', card: '0..1', type: 'CashAccount40', desc: 'Konto beim CdtrAgt.' },
          {
            name: 'Cdtr',
            card: '1',
            type: 'PartyIdentification135',
            desc: 'Empfänger / Begünstigter.',
            children: [
              { name: 'Nm', card: '0..1', type: 'Max140Text', desc: 'Name des Empfängers.' },
              { name: 'PstlAdr', card: '0..1', type: 'PostalAddress24', desc: 'Strukturierte Adresse — CBPR+ Pflicht.', versionFlag: 'CBPR+' },
              { name: 'Id', card: '0..1', type: 'Party38Choice', desc: 'OrgId / PrvtId.' },
            ],
          },
          { name: 'CdtrAcct', card: '0..1', type: 'CashAccount40', desc: 'Empfänger-Konto.' },
          { name: 'UltmtCdtr', card: '0..1', type: 'PartyIdentification135', desc: 'Ultimate Creditor (COBO).' },
          { name: 'InstrForCdtrAgt', card: '0..N', type: 'InstructionForCreditorAgent3', desc: 'Instruction Codes für Empfänger-Bank (CHQB, HOLD, PHOB, TELB).' },
          { name: 'InstrForNxtAgt', card: '0..N', type: 'InstructionForNextAgent1', desc: 'Instruction Codes für nächsten Agenten in der Kette.' },
          { name: 'Purp', card: '0..1', type: 'Purpose2Choice', desc: 'External Purpose Code (SUPP, SALA, INTC, TAXS).' },
          { name: 'RgltryRptg', card: '0..N', type: 'RegulatoryReporting3', desc: 'AWV-Meldung / SAFE / Cross-Border-Regulatory Reporting.' },
          { name: 'Tax', card: '0..1', type: 'TaxInformation8', desc: 'Steuerinformationen bei steuerrelevanten Transfers.' },
          { name: 'RltdRmtInf', card: '0..N', type: 'RemittanceLocation7', desc: 'Verweis auf externen Remittance-Advice (Electronic Address / Postal).' },
          {
            name: 'RmtInf',
            card: '0..1',
            type: 'RemittanceInformation16',
            desc: 'Verwendungszweck (CBPR+: max 140 Zeichen unstrukturiert, strukturiert bevorzugt).',
            children: [
              { name: 'Ustrd', card: '0..N', type: 'Max140Text', desc: 'Unstrukturierter Verwendungszweck. CBPR+: max. 1 Instanz, 140 Zeichen.', versionFlag: 'CBPR+' },
              { name: 'Strd', card: '0..N', type: 'StructuredRemittanceInformation16', desc: 'Strukturierter Verwendungszweck (Referenced Document, Creditor/Debtor Reference).' },
            ],
          },
        ],
      },
    ],
  },
];

const migrationChangesToCBPR: MigrationChange[] = [
  { field: 'PmtId/UETR', oldValue: 'optional', newValue: 'Pflicht (UUID v4) — gpi Tracker', type: 'changed' },
  { field: 'Dbtr/PstlAdr', oldValue: 'AdrLine (Freitext) erlaubt', newValue: 'Strukturierte Adresse (StrtNm, TwnNm, Ctry) Pflicht ab Nov 2025', type: 'changed' },
  { field: 'Cdtr/PstlAdr', oldValue: 'AdrLine (Freitext) erlaubt', newValue: 'Strukturierte Adresse Pflicht ab Nov 2025', type: 'changed' },
  { field: 'RmtInf/Ustrd', oldValue: '0..N × Max140Text', newValue: 'CBPR+: genau 1 Instanz, 140 Zeichen (Truncation-Rule)', type: 'changed' },
  { field: 'ChrgBr', oldValue: 'optional in einigen Versionen', newValue: 'Pflicht — SHAR / DEBT / CRED / SLEV', type: 'changed' },
  { field: 'BIC-Identifikation', oldValue: 'BIC', newValue: 'BICFI (BusinessIdentifierCode, Financial Institution)', type: 'changed' },
  { field: 'ChrgsInf', oldValue: '— nicht strukturiert', newValue: 'Charges7 mit Amount + Agent — gpi Fee-Transparency', type: 'new' },
  { field: 'SttlmTmIndctn', oldValue: '— nicht vorhanden', newValue: 'DbtDtTm / CdtDtTm für gpi SLA-Monitoring', type: 'new' },
];

registerFormat({
  formatName: 'pacs.008',
  schemaUriPattern: 'urn:iso:std:iso:20022:tech:xsd:pacs.008.001.<v>',
  region: 'Global (Interbank)',
  characterSet: 'utf-8',
  rejectCodeGroup: 'iso20022',
  structure,
  migrations: [
    {
      label: 'pacs.008.001.02 → 001.001.08 (CBPR+ Baseline)',
      fromVersion: '001.001.02',
      toVersion: '001.001.08',
      changes: migrationChangesToCBPR,
    },
  ],
  featureDefs: [
    {
      match: /CBPR\+/i,
      name: 'CBPR+ Migration (SWIFT Nov 2025)',
      what: 'Cross-Border Payments and Reporting Plus — SWIFT-weite Ablösung von MT103 durch pacs.008.001.08 bis November 2025. Strukturierte Adressen, UETR, BICFI.',
      tokens: ['CBPR+', 'pacs.008.001.08', 'MT103'],
    },
    {
      match: /UETR/,
      name: 'UETR-Tracking (gpi)',
      what: 'Unique End-to-end Transaction Reference (UUID v4) — End-to-End-Verfolgbarkeit über SWIFT gpi Tracker. In CBPR+ Pflicht pro Transaktion.',
      tokens: ['UETR', 'PmtId', 'gpi'],
    },
    {
      match: /ChrgBr|SHAR|OUR|BEN|DEBT|CRED/,
      name: 'Charges-Handling (SHA/OUR/BEN)',
      what: 'ChargeBearer steuert Gebührenlast: DEBT (OUR) = Zahler trägt alle Gebühren; CRED (BEN) = Empfänger trägt; SHAR (SHA) = geteilt. ChrgsInf dokumentiert angefallene Agent-Gebühren.',
      tokens: ['ChrgBr', 'SHAR', 'DEBT', 'CRED', 'ChrgsInf'],
    },
    {
      match: /PrvsInstgAgt|IntrmyAgt|Agent[- ]?Chain/i,
      name: 'Agent-Chain (PrvsInstgAgt / IntrmyAgt)',
      what: 'Cross-Border-Routing über Korrespondenzbanken: PrvsInstgAgt1..3 dokumentiert bereits durchlaufene Agenten, IntrmyAgt1..3 definiert geplante Zwischenstationen.',
      tokens: ['PrvsInstgAgt1', 'PrvsInstgAgt2', 'PrvsInstgAgt3', 'IntrmyAgt1', 'IntrmyAgt2', 'IntrmyAgt3'],
    },
    {
      match: /SettlementMethod|INDA|INGA|COVE|CLRG/i,
      name: 'Settlement-Method (INDA/INGA/COVE/CLRG)',
      what: 'Wie wird zwischen den Banken verrechnet: INDA = über Konto beim Instructed Agent; INGA = beim Instructing Agent; COVE = Cover Payment (pacs.009 COV); CLRG = über Clearing-System.',
      tokens: ['SttlmMtd', 'INDA', 'INGA', 'COVE', 'CLRG'],
    },
    {
      match: /BICFI/,
      name: 'BICFI (Business Identifier Code, Financial Institution)',
      what: 'Ersetzt das alte BIC/BICOrBEI-Element. Durchgängig in allen Agent-Feldern von pacs.008.',
      tokens: ['BICFI', 'FinInstnId'],
    },
  ],
});
